name: 'lighthouse-ci'
description: 'Get lighthouse results on every PR'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  build-and-serve-script:
    description: 'The npm-script to run that builds and serves your project'
    default: 'build:serve'
    required: true
runs:
  using: 'node12'
  main: './dist/test.js'
